Repository Skiylia-Lang/PySkiylia, pull requests merged in 2021-03, with the labels that each got.

#62 Update release-drafter.yml
  .github/release-drafter.yml
Labels: documentation, minor

#65 Update README.md
  ExampleCode/README.md
Labels: documentation

#67 Variable resolver
  ExampleCode/ControlFlow/ForTest.skiy
  ExampleCode/Fibonacci.skiy
  PySkiylia/ASTPrinter.py
  PySkiylia/Environment.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Resolver.py
  PySkiylia/__pycache__/ASTPrinter.cpython-39.pyc
  PySkiylia/__pycache__/AbstractSyntax.cpython-39.pyc
  PySkiylia/__pycache__/Environment.cpython-39.pyc
  PySkiylia/__pycache__/Interpreter.cpython-39.pyc
  PySkiylia/__pycache__/Lexer.cpython-39.pyc
  PySkiylia/__pycache__/Parser.cpython-39.pyc
  PySkiylia/__pycache__/Primitives.cpython-39.pyc
  PySkiylia/__pycache__/PySkiylia.cpython-39.pyc
  PySkiylia/__pycache__/Resolver.cpython-39.pyc
  PySkiylia/__pycache__/SkiyliaCallable.cpython-39.pyc
  PySkiylia/__pycache__/Tokens.cpython-39.pyc
Labels: patch

#68 Classes
  ExampleCode/Classes/classmegatest.skiy
  ExampleCode/ExtendedBakusNaurForm.txt
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/__pycache__/ASTPrinter.cpython-39.pyc
  PySkiylia/__pycache__/AbstractSyntax.cpython-39.pyc
  PySkiylia/__pycache__/Environment.cpython-39.pyc
  PySkiylia/__pycache__/Interpreter.cpython-39.pyc
  PySkiylia/__pycache__/Parser.cpython-39.pyc
  PySkiylia/__pycache__/PySkiylia.cpython-39.pyc
  PySkiylia/__pycache__/Resolver.cpython-39.pyc
  PySkiylia/__pycache__/SkiyliaCallable.cpython-39.pyc
Labels: enhancement

#69 fixed class initialisers not binding propery
  ExampleCode/Classes/classmegatest.skiy
  PySkiylia/SkiyliaCallable.py
  PySkiylia/__pycache__/ASTPrinter.cpython-39.pyc
  PySkiylia/__pycache__/AbstractSyntax.cpython-39.pyc
  PySkiylia/__pycache__/Interpreter.cpython-39.pyc
  PySkiylia/__pycache__/Parser.cpython-39.pyc
  PySkiylia/__pycache__/PySkiylia.cpython-39.pyc
  PySkiylia/__pycache__/Resolver.cpython-39.pyc
  PySkiylia/__pycache__/SkiyliaCallable.cpython-39.pyc
Labels: bug, enhancement

#70 feature: class Inheritance
  ExampleCode/Classes/superclass.skiy
  ExampleCode/ExtendedBakusNaurForm.txt
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
Labels: enhancement

#72 Release 0.6.0
  .github/release-drafter.yml
  ExampleCode/Classes/classmegatest.skiy
  ExampleCode/Classes/superclass.skiy
  ExampleCode/ControlFlow/ForTest.skiy
  ExampleCode/ExtendedBakusNaurForm.txt
  ExampleCode/Fibonacci.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Environment.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/__pycache__/ASTPrinter.cpython-39.pyc
  PySkiylia/__pycache__/AbstractSyntax.cpython-39.pyc
  PySkiylia/__pycache__/Environment.cpython-39.pyc
  PySkiylia/__pycache__/Expr.cpython-39.pyc
  PySkiylia/__pycache__/Interpreter.cpython-39.pyc
  PySkiylia/__pycache__/Lexer.cpython-39.pyc
  PySkiylia/__pycache__/Parser.cpython-39.pyc
  PySkiylia/__pycache__/Primitives.cpython-39.pyc
  PySkiylia/__pycache__/PySkiylia.cpython-39.pyc
  PySkiylia/__pycache__/SkiyliaCallable.cpython-39.pyc
  PySkiylia/__pycache__/Tokens.cpython-39.pyc
Labels: enhancement

#73 New primitives
  ExampleCode/BasicGrammar.skiy
  ExampleCode/ExtendedBakusNaurForm.txt
  ExampleCode/Fibonacci.skiy
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/Primitives.py
  PySkiylia/PySkiylia.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: patch

#74 version 0.6.1
  ExampleCode/BasicGrammar.skiy
  ExampleCode/ExtendedBakusNaurForm.txt
  ExampleCode/Fibonacci.skiy
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/Primitives.py
  PySkiylia/PySkiylia.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: patch

#75 exponentiation incorrect
  ExampleCode/BasicGrammar.skiy
  PySkiylia/Interpreter.py
Labels: bug

#78 Develop
  .all-contributorsrc
  ExampleCode/README.md
  ExampleCode/classExample.skiy
  ExampleCode/factorial.skiy
  PySkiylia/Lexer.py
  PySkiylia/PySkiylia.py
  README.md
Labels: bug, patch

#79 Increment operators
  ExampleCode/Assignment/Augmented_Assignment.skiy
  ExampleCode/Assignment/Variables/Declare_And_Reassign.py
  ExampleCode/Assignment/Variables/Declare_And_Reassign.skiy
  ExampleCode/Assignment/Variables/Declare_and_self_Reassign.skiy
  ExampleCode/Assignment/Variables/Explicit_Declaration.skiy
  ExampleCode/Assignment/Variables/Implicit_Declaration.py
  ExampleCode/Grammar/BasicGrammar.skiy
  ExampleCode/Grammar/ExampleGrammar.skiy
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/Grammar/FullGrammar.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Tokens.py
Labels: patch

#80 Ternary operator
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/Grammar/FullGrammar.skiy
  ExampleCode/Logicals/Conditionals.skiy
  ExampleCode/Logicals/Equality.py
  ExampleCode/Logicals/Equality.skiy
  ExampleCode/Logicals/LogicalOperation.py
  ExampleCode/Logicals/LogicalOperation.skiy
  ExampleCode/Logicals/Not.py
  ExampleCode/Logicals/not.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/Resolver.py
  PySkiylia/Tokens.py
Labels: patch

#81 Break and continue
  ExampleCode/ControlFlow/ForTest.skiy
  ExampleCode/ControlFlow/Interuptions.skiy
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/Grammar/FullGrammar.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: enhancement

#82 More comparisons
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/Grammar/FullGrammar.skiy
  ExampleCode/Logicals/Equality.skiy
  ExampleCode/Logicals/FuzzyEquality.skiy
  ExampleCode/Logicals/StrictEquality.skiy
  ExampleCode/Logicals/comparison.skiy
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Tokens.py
Labels: enhancement

#83 v0.7.0
  ExampleCode/Assignment/Augmented_Assignment.skiy
  ExampleCode/Assignment/Variables/Declare_And_Reassign.py
  ExampleCode/Assignment/Variables/Declare_And_Reassign.skiy
  ExampleCode/Assignment/Variables/Declare_and_self_Reassign.skiy
  ExampleCode/Assignment/Variables/Explicit_Declaration.skiy
  ExampleCode/Assignment/Variables/Implicit_Declaration.py
  ExampleCode/ControlFlow/ForTest.skiy
  ExampleCode/ControlFlow/Interuptions.skiy
  ExampleCode/Grammar/BasicGrammar.skiy
  ExampleCode/Grammar/ExampleGrammar.skiy
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/Grammar/FullGrammar.skiy
  ExampleCode/Logicals/Conditionals.skiy
  ExampleCode/Logicals/Equality.py
  ExampleCode/Logicals/Equality.skiy
  ExampleCode/Logicals/FuzzyEquality.skiy
  ExampleCode/Logicals/LogicalOperation.py
  ExampleCode/Logicals/LogicalOperation.skiy
  ExampleCode/Logicals/Not.py
  ExampleCode/Logicals/StrictEquality.skiy
  ExampleCode/Logicals/comparison.skiy
  ExampleCode/Logicals/not.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/Primitives.py
  PySkiylia/PySkiylia.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: enhancement

#84 update readme and include important syntax
  ExampleCode/README.md
  ExampleCode/Tribonacci.skiy
  ExampleCode/classExample.skiy
  PySkiylia/Interpreter.py
  PySkiylia/Primitives.py
  PySkiylia/PySkiylia.py
  PySkiylia/README.md
  README.md
Labels: patch

#86 Update readme
  ExampleCode/README.md
  PySkiylia/README.md
  README.md
Labels: skip-changelog

#87 update readme links to use the organisation repo
  ExampleCode/README.md
  PySkiylia/README.md
  README.md
Labels: skip-changelog

#89 Better number implementation
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: patch

#90 Import syntax
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  ExampleCode/ImportingCodeScripts/importee.skiy
  ExampleCode/ImportingCodeScripts/importer.skiy
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/PySkiylia.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
  PySkiylia/Tokens.py
Labels: enhancement

#91 Elif and input
  ExampleCode/Assignment/ArrayTest.skiy
  ExampleCode/ControlFlow/if-elif-else.skiy
  ExampleCode/FileIO/ReadFile.skiy
  ExampleCode/FileIO/WriteFile.skiy
  ExampleCode/Grammar/ExtendedBakusNaurForm.txt
  PySkiylia/ASTGenerator.py
  PySkiylia/ASTPrinter.py
  PySkiylia/AbstractSyntax.py
  PySkiylia/Interpreter.py
  PySkiylia/Parser.py
  PySkiylia/Primitives.py
  PySkiylia/PySkiylia.py
  PySkiylia/SkiyliaCallable.py
Labels: enhancement

#92 Codefactor improvements
  ExampleCode/Assignment/Variables/Implicit_Declaration.py
  PySkiylia/ASTPrinter.py
  PySkiylia/Interpreter.py
  PySkiylia/Lexer.py
  PySkiylia/Parser.py
  PySkiylia/Resolver.py
  PySkiylia/SkiyliaCallable.py
Labels: patch
